//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAgile
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentPrice
    {
        public EquipmentPrice()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int Id_model { get; set; }
        public int Id_equipment { get; set; }
        public float Price { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Model Model { get; set; }
    }
}
