//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAgile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.EquipmentPrices = new HashSet<EquipmentPrice>();
        }
    
        public int id { get; set; }
        public int id_make { get; set; }
        public string name { get; set; }
        public float price { get; set; }
    
        public virtual ICollection<EquipmentPrice> EquipmentPrices { get; set; }
        public virtual Make Make { get; set; }
    }
}
