//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAgile
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Model
    {
        public Model()
        {
            this.EquipmentPrices = new HashSet<EquipmentPrice>();
        }

        public int Id { get; set; }
        public int Id_make { get; set; }
        [Required]
        [Display(Name = "Nazwa")]
        public string Name { get; set; }
        [Range(0, float.MaxValue, ErrorMessage = "Wartoœæ musi byæ liczb¹ nieujemn¹")]
        [Display(Name = "Cena bazowa")]
        public float Price { get; set; }

        public virtual ICollection<EquipmentPrice> EquipmentPrices { get; set; }
        public virtual Make Make { get; set; }
    }
}
