//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAgile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int id_seller { get; set; }
        public int id_car { get; set; }
        public int id_color { get; set; }
        public int id_state { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.DateTime> realization { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual EquipmentPrice EquipmentPrice { get; set; }
        public virtual State State { get; set; }
    }
}
