//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseAgile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public int id { get; set; }
        public Nullable<System.Guid> id_user { get; set; }
        public Nullable<int> id_branch { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
